language: scala
scala: 2.11.7
jdk:
    - oraclejdk8
before_install:
    - nvm install 5
    - nvm use 5
    - npm install -g grunt-cli
install:
    - npm install
    - grunt --version
    - jspm registry export github
    - jspm config registries.github.remote https://github.jspm.io
    - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
    - jspm config registries.github.handler jspm-github
    - jspm install
script:
    - grunt --stack validate test
    - sbt ++$TRAVIS_SCALA_VERSION compile test assets riffRaffArtifact && grunt --stack bundle upload
env:
    global:
        # JSPM token
        - secure: Fq9NhK56PaheU0i2hmXMgJ6p6P0Sb+zDjjTexoTAmgoJ48I16PS5+PWkJ8m6vs+w152uugv8ngsQxQr3/kMwvPufAy4a4hdzEliVRVPUSOPIhRDBoxR692GmPgJwdI7dmVRXpprIIsOJpPEyFuFpoS4Kkd7jscTnZhmlujuY30o3SO96oLT8Ad6vZxQT2VRTs1Cck0k8P83PvCJI4cXBLVaytIW3VbjJUcph/AYyyfH/YQ7NGCFkpJDo6IebGV/kdz9Azcx8W47uVHCbw7OD7wWEbWHj6YCXFsJben7fyVIFAsTNSYBQKx0pAAPKHDMFqqDEiNkp0XRSQq9AksYOQ0CZlrU8DaDg0gXKc5FbrQLzp5snIXbvvJe6XWJfNxE1wxdw3jAhd8oANBANEgcN+6QIC3J4iu9VJYF/rAnf1WhkHgW/7cxP9MK62vKiinwEXLESL0gxofYeSTW6ykzrG6DnhJfnz2JYMShmb8V9iFqlASfzU4C/RY5RhcfSHPlE4RhR8bHqD2Fb+lXY7S+jX7Nf0FuaKfZcya2K+wjKuY+aSgR6/NXGYx3PwIAtERL3bkH+F7+G4hAtmUYPad4mgznIWFAhRcTlMrQtgE/rNOqgtlD4fGVbcHW7ZNXa0CWFHvnomCMHhXT0EaXoRK8y6yBUK9+E1Yy5zj1Z+Uj47GY=
        # RiffRaff upload keys and secret
        - secure: rqLMkxwFoViYYT+KulCa8vc7Q+8Od2hdD5L51/Cxre97Oe18Bx2+MtmvhpTNnjSDNjbvw6FXXeEWUg548+LvyIUwzTzWz7T+EnZVtXYWC45zr5966i7MC1vKRQO5VBvfoV62Y1EsbvFBHlFEVkyivo2vYZBW8EcInOvBH7mccAhXvsisVoV8jBjik2lA3rW1C3Hh5aVwvkgc/ajbzYvIBf36iexDZDPaRAibU+/d4WRUShYp+xCS/FhE7AW8GiWNcQF3VHRmY/1LXTSuaLa/zaIA+LT5u9K1q560krTEsWH8MMw8aflhCQCy0eYxazl+6/3d14Hwn1fh8ixUdEaWuitLMCQ43BFcaw688AVq6nKrQBNeZIo0jhhIPLJXiTM/OLHv6gJAHZVzB4g4QMt131JQgh6dPA5A7gT102csDQxsHFe6OoNRsyNY9UewAlkYR3jmmWENvl0A75jexAvHRzIZTqUSxnuZydMaZ+EhXDRCVGj8dUuxyk/A6CwFmgnxo+U4lN8ezjV0b4N0W6zOfwhLz2S5bMfXlrSn21mgwSgD5sjq03o76/OuLLW8mDagA4g2xzQCI/bZdeUGHirV90db/ZuM5yWwq6iflu41Fi+h6ejxg1s5MS62D4viQlKY6Vczz7eZ6Z26CywLrau5a4XbqRPo90s965ZrU4ZIEUE=
        - secure: GKLV4apiJXpovMqYq7cEGHRjYNsFtWBbca5UDy4n4S4Hlpbz14VtFG8iVmQEHAuQ8Wia7o8+WKfcdUKUoLFFMazk/yuA/NdKX6uyYSV9itBYEMPZBzR0Kta3bdSPOgeHDZixxvcbrj47a0XffPWbwEuQ7tNWlHTmaagvogBY6cXJ8J0CgS3FwAMpTfeakaoIMWGHNr0A5MgKlqxhfOxZIMxjwJToWxWk1E2fkJZTGSSzQdn2OdupAf98i8Y5cZ7hsZIRZ5N5dQzzDKrS+iNXHPM7ioXJLFgwf56QeReHyaWlk3Rg5ak911B6ssLSY+O1/AFJgG8B90VBmHsGxGPj9aDuhzBg00pRzVA9+lFi4qtA76vcKJQnZKQ44werZVfDsf8xjLiw3+MvunXi4zFhIiztBE+HnVgGrkjrra6wtW4GEl3wdFfbyQtsePuF1uxBduq43eue49YqcoIevAuEjeJVtBdAXL2eHFLZHTjqi9ZKDLVgrBU7CvsLR8JbtHp0BOm/f3N80lCo20kDDf7MVnlEJ2Up40wUM9UNtdGu57Ha3C5oh5/BJXg9SoTvXsr0BHh/V9da4khjxOfawQ/KedVkQoUF94fsQ00zyvOC+4ozfMY+JGa1c1gfGcX5kQTcyu0824Pn4h/bK0p4Vg7DuzxMbl6oOunXNudT1a4Ltno=
cache:
    directories:
        - node_modules
        - public/src/jspm_packages
        - ~/.ivy2/cache
        - ~/.sbt/boot/
        - ~/.nvm/
before_cache:
    - du -h -d 1 $HOME/.ivy2/
    - du -h -d 2 $HOME/.sbt/
    # Tricks to avoid unnecessary cache updates
    - find $HOME/.sbt -name "*.lock" -type f -delete
    - find $HOME/.ivy2 -name "ivydata-*.properties" -type f -delete
