language: scala
scala: 2.11.7
jdk:
- oraclejdk8
before_install:
- nvm install 5
- nvm use 5
- npm install -g grunt-cli
install:
- npm install
- grunt --version
- jspm registry export github
- jspm config registries.github.remote https://github.jspm.io
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm config registries.github.handler jspm-github
- jspm install
script:
- grunt --stack validate test && sbt ++$TRAVIS_SCALA_VERSION compile test assets && grunt --stack bundle && sbt ++$TRAVIS_SCALA_VERSION riffRaffUpload
env:
  global:
  - secure: Fq9NhK56PaheU0i2hmXMgJ6p6P0Sb+zDjjTexoTAmgoJ48I16PS5+PWkJ8m6vs+w152uugv8ngsQxQr3/kMwvPufAy4a4hdzEliVRVPUSOPIhRDBoxR692GmPgJwdI7dmVRXpprIIsOJpPEyFuFpoS4Kkd7jscTnZhmlujuY30o3SO96oLT8Ad6vZxQT2VRTs1Cck0k8P83PvCJI4cXBLVaytIW3VbjJUcph/AYyyfH/YQ7NGCFkpJDo6IebGV/kdz9Azcx8W47uVHCbw7OD7wWEbWHj6YCXFsJben7fyVIFAsTNSYBQKx0pAAPKHDMFqqDEiNkp0XRSQq9AksYOQ0CZlrU8DaDg0gXKc5FbrQLzp5snIXbvvJe6XWJfNxE1wxdw3jAhd8oANBANEgcN+6QIC3J4iu9VJYF/rAnf1WhkHgW/7cxP9MK62vKiinwEXLESL0gxofYeSTW6ykzrG6DnhJfnz2JYMShmb8V9iFqlASfzU4C/RY5RhcfSHPlE4RhR8bHqD2Fb+lXY7S+jX7Nf0FuaKfZcya2K+wjKuY+aSgR6/NXGYx3PwIAtERL3bkH+F7+G4hAtmUYPad4mgznIWFAhRcTlMrQtgE/rNOqgtlD4fGVbcHW7ZNXa0CWFHvnomCMHhXT0EaXoRK8y6yBUK9+E1Yy5zj1Z+Uj47GY=
  - secure: rqLMkxwFoViYYT+KulCa8vc7Q+8Od2hdD5L51/Cxre97Oe18Bx2+MtmvhpTNnjSDNjbvw6FXXeEWUg548+LvyIUwzTzWz7T+EnZVtXYWC45zr5966i7MC1vKRQO5VBvfoV62Y1EsbvFBHlFEVkyivo2vYZBW8EcInOvBH7mccAhXvsisVoV8jBjik2lA3rW1C3Hh5aVwvkgc/ajbzYvIBf36iexDZDPaRAibU+/d4WRUShYp+xCS/FhE7AW8GiWNcQF3VHRmY/1LXTSuaLa/zaIA+LT5u9K1q560krTEsWH8MMw8aflhCQCy0eYxazl+6/3d14Hwn1fh8ixUdEaWuitLMCQ43BFcaw688AVq6nKrQBNeZIo0jhhIPLJXiTM/OLHv6gJAHZVzB4g4QMt131JQgh6dPA5A7gT102csDQxsHFe6OoNRsyNY9UewAlkYR3jmmWENvl0A75jexAvHRzIZTqUSxnuZydMaZ+EhXDRCVGj8dUuxyk/A6CwFmgnxo+U4lN8ezjV0b4N0W6zOfwhLz2S5bMfXlrSn21mgwSgD5sjq03o76/OuLLW8mDagA4g2xzQCI/bZdeUGHirV90db/ZuM5yWwq6iflu41Fi+h6ejxg1s5MS62D4viQlKY6Vczz7eZ6Z26CywLrau5a4XbqRPo90s965ZrU4ZIEUE=
  - secure: GKLV4apiJXpovMqYq7cEGHRjYNsFtWBbca5UDy4n4S4Hlpbz14VtFG8iVmQEHAuQ8Wia7o8+WKfcdUKUoLFFMazk/yuA/NdKX6uyYSV9itBYEMPZBzR0Kta3bdSPOgeHDZixxvcbrj47a0XffPWbwEuQ7tNWlHTmaagvogBY6cXJ8J0CgS3FwAMpTfeakaoIMWGHNr0A5MgKlqxhfOxZIMxjwJToWxWk1E2fkJZTGSSzQdn2OdupAf98i8Y5cZ7hsZIRZ5N5dQzzDKrS+iNXHPM7ioXJLFgwf56QeReHyaWlk3Rg5ak911B6ssLSY+O1/AFJgG8B90VBmHsGxGPj9aDuhzBg00pRzVA9+lFi4qtA76vcKJQnZKQ44werZVfDsf8xjLiw3+MvunXi4zFhIiztBE+HnVgGrkjrra6wtW4GEl3wdFfbyQtsePuF1uxBduq43eue49YqcoIevAuEjeJVtBdAXL2eHFLZHTjqi9ZKDLVgrBU7CvsLR8JbtHp0BOm/f3N80lCo20kDDf7MVnlEJ2Up40wUM9UNtdGu57Ha3C5oh5/BJXg9SoTvXsr0BHh/V9da4khjxOfawQ/KedVkQoUF94fsQ00zyvOC+4ozfMY+JGa1c1gfGcX5kQTcyu0824Pn4h/bK0p4Vg7DuzxMbl6oOunXNudT1a4Ltno=
  - secure: Yji3AJqKWnSD9rPJWUd9qhFdrsLhC4ftJ3II6Qtp/UW40zGqpecWTCa6uSDFk+qn4UanygggxbpVggXsKzv1qKo5/b6EETKGtwWcU0RDo7QgoDIm/QJ9xcghZGintOzXJEovgqVM67Zignrcwr0M45roDJNuZzEhUMUedkHeLMMDYUkwQjgiYyv6yp8yEbuVt6BIzj18AyU9zmTM2MULHSD6RfWFdyCzntDytvvDvmYIAi/hJfDinyvAG711isNKHojRt+ZzuQNeQL+bpIhSirvy0v8tgJDoen8KcgsCoqQjD99mgGl8uuZTbA9yeAx1H65ETDvjAl7L1RH06GuCEH919Atphlx8nnCxTyzV+NFjKRdPSfUrlCUeCN5KpyeFFx3FhRRvUElc/YMroEsGommK9o7/2h7mFgXRt82S7aPQYZtb3A0SGLxQn03PIVanXtYhFotVAonNTrwM98249B7ZaAuZATz6FKNIhNPw6yMPDZ5cEvEVpVXjfJaTQzI+f1ryxrqiZVNS1ILhmSwH2IOcfy7tUYn3ws4G5uF+ycEPwczObhMwSUC9ph9KuiCJ+8WN7B2FqLDCbwpq7vxlHel0dmRAC3JZLmB/OPE8+DaosqdUgf3vb3JOB91PE7cnWi6d2hlPJSXkKmE3VqiFFBcQnXp8lVREmewMZ4FfbU4=
  - secure: MJABLp7U5yR51OyRSzo+FO/QDxQSZdpUVO0KaRWs4kdo0n3ztv7IskIAgiNxeCZuoXj99sOYfKbn4Zk3owHER9//6BO15PLjKg6Nnh14/swi8uCOsZyujI2D+/z5r+U5iPttfYtk16uH4ZmoYX7e05QMGWmL8ZnWS6JPSra7NmsZf9CHMzPxBLYbEIcBQb1FwVwh1tLN9wxCU7MzOYEmxID7U46F7QkbYt5uwnY+zYvychvnyUshm36eZITp9MVVyOryI1xrra1AbuF5Zv8RXibT5nAKZEm+NVwN6NmrM9WwFCL++89fs7wSa/yLvM1+LkUmPhUELpFQW5oIUswK9k5VYqa7+7Z5Ahef6LA/kVeRQ46qj2JzOQmd3fguuibmQ+OiNQbHWfN7rOVAWBWlYdxHviVXuTUseaKhK0fpQ28G1PNYZ50gNrnPxbaA1xQxd66PvvbcJpV96xf68hwze99mySGpUi96YblWrZsDdflTndJOS/HgRQxkC+WcrIY7hgByy5LETNuhNEZVVaZKx7FGgfRaQyy/qfvH424+EGJylzRYU3O3kbZuoF0nulJ6x0rNlTHkKqpFGm/sQfE2csbQDTuULhPSWVfyctlF+Az3t9OKtq2DhgsHhV7XEybX5ckzJCBu/UZjylZS2jWdqRG18SYmJjMJ+V0RMJ5EAUU=
cache:
  directories:
  - node_modules
  - public/src/jspm_packages
  - ~/.ivy2/cache
  - ~/.sbt/boot/
  - ~/.nvm/
before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2 -name "ivydata-*.properties" -type f -delete
